import type { Checklist, DocMeta, DocReviewStatus } from "../help.types";

// Section E — smoke-test checklists. Curated, read-only verification lists per
// module. Destructive items are flagged productionRisk + doNotTestOnRealData so
// they are only ever exercised against a disposable tenant, never live data.

const meta = (moduleOwner: string, reviewStatus: DocReviewStatus = "reviewed"): DocMeta => ({
  version: "1.0",
  lastUpdatedBy: "Platform Engineering",
  lastUpdated: "2026-07-07",
  reviewedBy: reviewStatus === "reviewed" ? "Platform Owner" : null,
  reviewStatus,
  nextReviewDate: "2026-10-07",
  moduleOwner,
});

export const checklists: Checklist[] = [
  {
    id: "invoice-checklist",
    title: "Invoice module smoke test",
    module: "invoice",
    route: "/super-admin/invoices",
    warning: "Voiding an invoice is a permanent state change — never void a real invoice to test.",
    items: [
      { text: "Open the Invoices list and confirm it loads.", expectedResult: "Invoices render with tenant, amount, period and status.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Filter invoices by status (paid/overdue/void).", expectedResult: "The list filters correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a single invoice's detail view.", expectedResult: "Full details display without error.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Issue a test invoice for a disposable tenant.", expectedResult: "Invoice is created with correct details.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Void the test invoice and record a reason.", expectedResult: "Invoice moves to a voided state with the reason shown.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "tenant-checklist",
    title: "Tenant module smoke test",
    module: "tenant",
    route: "/super-admin/platform/tenants",
    warning: "Suspension blocks every user in a tenant — only test suspend/reactivate on a disposable tenant.",
    items: [
      { text: "Open the Tenants list and confirm it loads.", expectedResult: "Tenants render with name, type and status.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Search for a tenant by name.", expectedResult: "The matching tenant is found.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a tenant's detail view.", expectedResult: "Tenant details and status display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Create a disposable test tenant.", expectedResult: "Tenant is created with the correct type.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Suspend the test tenant, then reactivate it.", expectedResult: "Status toggles suspended then active as expected.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "settings-checklist",
    title: "Settings (N) smoke test",
    module: "settings_n",
    route: "/super-admin/settings",
    warning: null,
    items: [
      { text: "Open the Settings module and confirm it loads.", expectedResult: "Settings sections render without error.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Review each settings section for readable values.", expectedResult: "Current configuration is displayed clearly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Change a low-impact display setting and save.", expectedResult: "The change persists and reloads correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm optional-dependency settings show their configured/not-configured state.", expectedResult: "Optional integrations report status accurately.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "saas-billing-checklist",
    title: "SaaS Billing (C) smoke test",
    module: "billing_c",
    route: "/super-admin/packages",
    warning: "Changing a live package affects entitlements for tenants on it — test package edits on a disposable package.",
    items: [
      { text: "Open the packages list and confirm it loads.", expectedResult: "Packages render with names, pricing and features.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a package's detail view.", expectedResult: "Package details display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Create a disposable test package.", expectedResult: "Package is created with the entered values.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Edit the test package's pricing or features.", expectedResult: "Changes persist correctly.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "subscription-checklist",
    title: "Subscription (D) smoke test",
    module: "subscriptions_d",
    route: "/super-admin/subscriptions",
    warning: "Changing a real subscription affects a tenant's access — test renewals on a disposable tenant.",
    items: [
      { text: "Open the Subscriptions list and confirm it loads.", expectedResult: "Subscriptions render with tenant, package and dates.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Sort by upcoming renewal date.", expectedResult: "Soonest renewals surface at the top.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a subscription's detail view.", expectedResult: "Period and package display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Renew a disposable tenant's subscription.", expectedResult: "Expiry extends and the package is correct.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "platform-admin-users-checklist",
    title: "Platform Admin Users (I) smoke test",
    module: "admins_i",
    route: "/super-admin/admins",
    warning: "Disabling an admin removes their access — never test disable on a real admin's account.",
    items: [
      { text: "Open the platform admin list and confirm it loads.", expectedResult: "Admins render with role and status.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open an admin's detail view.", expectedResult: "Account details and role display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Invite a disposable test admin account.", expectedResult: "Invite is created and the account appears.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Disable the test admin account.", expectedResult: "Account is blocked from signing in.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Re-enable the test account.", expectedResult: "Account can sign in again.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("owner"),
  },
  {
    id: "rbac-checklist",
    title: "RBAC (H) smoke test",
    module: "rbac_h",
    route: "/super-admin/rbac",
    warning: "Role changes take effect immediately — test permission changes on a disposable test admin.",
    items: [
      { text: "Open the RBAC module and confirm it loads.", expectedResult: "Roles and permissions render clearly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Inspect a role's permission mapping.", expectedResult: "Permissions for the role display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Assign a role to a disposable test admin.", expectedResult: "The test admin gains exactly that role's access.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Change the test admin's role and verify access shifts.", expectedResult: "Newly granted actions work; revoked ones do not.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("owner"),
  },
  {
    id: "security-center-checklist",
    title: "Security Center (P) smoke test",
    module: "security_p",
    route: "/super-admin/security",
    warning: "A 2FA reset is security-sensitive — only test it on a disposable test admin.",
    items: [
      { text: "Open the Security Center and confirm it loads.", expectedResult: "Security posture and events render.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Review active sessions.", expectedResult: "Sessions list displays with enough detail to act.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Review recent security-relevant events.", expectedResult: "Events display in a readable, filterable way.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Reset 2FA for a disposable test admin.", expectedResult: "The test admin can enrol a fresh second factor.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Revoke a test session and confirm it ends.", expectedResult: "The targeted session is terminated.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "audit-console-checklist",
    title: "Audit Console (F) smoke test",
    module: "audit_f",
    route: "/super-admin/platform/audit",
    warning: null,
    items: [
      { text: "Open the Audit Console and confirm it loads.", expectedResult: "Audit events render in reverse-chronological order.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Filter by actor, module, action and date range.", expectedResult: "Filters narrow results accurately.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a single audit event's detail.", expectedResult: "Full event context displays.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm a recent known action appears in the log.", expectedResult: "The action is recorded with the correct actor.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Produce a small audit export for a narrow filter.", expectedResult: "Export contains exactly the filtered events.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("auditor", "needs_review"),
  },
  {
    id: "support-access-checklist",
    title: "Support Access (G) smoke test",
    module: "support_g",
    route: "/super-admin/platform/support",
    warning: "A support grant exposes tenant data — only test grants against a disposable tenant.",
    items: [
      { text: "Open Support Access and confirm it loads.", expectedResult: "Existing grants and their scopes render.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Review an existing grant's scope and expiry.", expectedResult: "Scope and duration display correctly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Start a narrowly scoped grant on a disposable tenant.", expectedResult: "Grant activates with the chosen scope and duration.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Revoke the grant and confirm it ends.", expectedResult: "Grant shows revoked and access stops.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "backup-restore-checklist",
    title: "Backup / Restore (J) smoke test",
    module: "backup_j",
    route: "/super-admin/backups",
    warning: "Restore can overwrite current data — NEVER run a restore against real data; use a disposable environment only.",
    items: [
      { text: "Open the Backup / Restore module and confirm it loads.", expectedResult: "Existing backups render with timestamps and status.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Create a new backup and confirm completion.", expectedResult: "A new backup appears with a success state.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Run a restore PREVIEW and review the planned changes.", expectedResult: "Preview describes what would change without applying it.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Execute a restore in a disposable environment only.", expectedResult: "Data is restored from the chosen backup.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Run post-restore verification checks.", expectedResult: "Recovered data matches the backup's expected state.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "data-export-checklist",
    title: "Data Export (K) smoke test",
    module: "export_k",
    route: "/super-admin/exports",
    warning: "Exports can contain sensitive data — use a disposable tenant and an approved delivery channel when testing.",
    items: [
      { text: "Open the Data Export Center and confirm it loads.", expectedResult: "Export options and history render.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Define a narrow export scope.", expectedResult: "Scope selection behaves as expected.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Generate a small test export for a disposable tenant.", expectedResult: "Export produces the expected file and is logged.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Confirm large-export capping guidance is shown.", expectedResult: "Oversized requests are guided toward chunking.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("auditor"),
  },
  {
    id: "observability-checklist",
    title: "Observability (L) smoke test",
    module: "observability_l",
    route: "/super-admin/observability",
    warning: null,
    items: [
      { text: "Open Health / Observability and confirm it loads.", expectedResult: "Health signals render clearly.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm core health signals are green.", expectedResult: "No critical red signals are present.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Check for recent error spikes.", expectedResult: "Error trends are visible and within normal range.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm the background worker reports healthy.", expectedResult: "Worker status shows running.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "jobs-console-checklist",
    title: "Jobs Console (M) smoke test",
    module: "jobs_m",
    route: "/super-admin/jobs",
    warning: "Some jobs are unsafe to run twice — understand a job before retrying it, and prefer a disposable target.",
    items: [
      { text: "Open Background Jobs and confirm it loads.", expectedResult: "Scheduled and recent jobs render with status.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Filter to failed or stuck jobs.", expectedResult: "Failures are easy to isolate.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Open a job's detail to read what it does.", expectedResult: "Job purpose and failure reason display.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Retry a safe, idempotent test job.", expectedResult: "The retried job reaches a success state.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "communication-admin-checklist",
    title: "Communication Admin (O) smoke test",
    module: "communication_o",
    route: "/super-admin/communication",
    warning: "A broadcast cannot be recalled — only send test broadcasts to a disposable test audience.",
    items: [
      { text: "Open Communication Admin and confirm it loads.", expectedResult: "Broadcast tools and history render.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Draft a message and preview its recipients.", expectedResult: "The intended audience is shown before sending.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm email/in-app delivery mode reflects mail-service configuration.", expectedResult: "Delivery mode is accurate for the current setup.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Send a test broadcast to a disposable test audience.", expectedResult: "The test audience receives it and status is shown.", productionRisk: true, doNotTestOnRealData: true },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "platform-overview-checklist",
    title: "Platform Overview (E) smoke test",
    module: "overview_e",
    route: "/super-admin/platform",
    warning: null,
    items: [
      { text: "Open the Platform Overview and confirm it loads.", expectedResult: "Summary tiles and trends render.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm tenant and subscription counts look correct.", expectedResult: "Counts match expectations at a glance.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Review recent platform activity.", expectedResult: "Recent activity displays without error.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm trend charts render (history starts at data-collection start).", expectedResult: "Trends display, with partial early history understood.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("owner"),
  },
  {
    id: "full-super-admin-regression",
    title: "Full Super Admin regression",
    module: "help_q",
    route: "/super-admin/help",
    warning: "Run only the read-only checks against production; perform all destructive checks on a disposable tenant/environment.",
    items: [
      { text: "Load every Super Admin module in turn and confirm each renders.", expectedResult: "All modules load without error.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm RBAC hides actions your role should not have.", expectedResult: "Unauthorised actions are not available.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Confirm Observability is green before deeper checks.", expectedResult: "Health signals are healthy.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Spot-check that recent actions appear in the Audit Console.", expectedResult: "Actions are logged with correct actors.", productionRisk: false, doNotTestOnRealData: false },
      { text: "Run each module's destructive checks against a disposable tenant only.", expectedResult: "Destructive flows behave correctly without touching real data.", productionRisk: true, doNotTestOnRealData: true },
      { text: "Record the overall regression result.", expectedResult: "A pass/fail summary is captured for the run.", productionRisk: false, doNotTestOnRealData: false },
    ],
    meta: meta("owner"),
  },
];
