// Super Admin Q — curated Module-Status register (Section B).
//
// CURATED METADATA, not live PR/deploy tracking. Status values are the CONFIRMED
// shipped state (owner-confirmed / this-session-verified). Ref fields
// (prNumber / prCommit / deployNumber / lastSmokeResult) are ONLY ever the REAL
// confirmed value and are `null` when a value is not known — NEVER fabricated.
// `lastUpdated` is the curation date of this register (2026-07-07).
//
// (Editable/admin-managed status is intentionally not implemented — see the PR's
// known-limitations. If added later it would live in a table and be audited.)

import type { ModuleStatusEntry } from "../help.types";

const CURATED = "2026-07-07";

export const moduleStatus: ModuleStatusEntry[] = [
  {
    key: "invoice",
    name: "Invoice",
    letter: null,
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "billing_admin",
    route: "/super-admin/invoices",
    docLink: "/super-admin/help?module=invoice",
    relatedLinks: [{ label: "Invoice SOP", href: "/super-admin/help?type=sop&module=invoice" }],
  },
  {
    key: "tenant",
    name: "Tenant / Institution",
    letter: null,
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "owner",
    route: "/super-admin/platform/tenants",
    docLink: "/super-admin/help?module=tenant",
    relatedLinks: [{ label: "Tenant onboarding SOP", href: "/super-admin/help?type=sop&module=tenant" }],
  },
  {
    key: "settings_n",
    name: "Settings",
    letter: "N",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/settings",
    docLink: "/super-admin/help?module=settings_n",
    relatedLinks: [],
  },
  {
    key: "billing_c",
    name: "SaaS Billing / Packages / Coupons / GST",
    letter: "C",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "billing_admin",
    route: "/super-admin/packages",
    docLink: "/super-admin/help?module=billing_c",
    relatedLinks: [{ label: "Payment gateway SOP", href: "/super-admin/help?type=sop&module=billing_c" }],
  },
  {
    key: "subscriptions_d",
    name: "Subscription Management",
    letter: "D",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "billing_admin",
    route: "/super-admin/subscriptions",
    docLink: "/super-admin/help?module=subscriptions_d",
    relatedLinks: [{ label: "Subscription renewal SOP", href: "/super-admin/help?type=sop&module=subscriptions_d" }],
  },
  {
    key: "admins_i",
    name: "Platform Admin User Management",
    letter: "I",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "owner",
    route: "/super-admin/admins",
    docLink: "/super-admin/help?module=admins_i",
    relatedLinks: [{ label: "Admin invite/disable SOP", href: "/super-admin/help?type=sop&module=admins_i" }],
  },
  {
    key: "rbac_h",
    name: "RBAC / Permission Enforcement",
    letter: "H",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "owner",
    route: "/super-admin/rbac",
    docLink: "/super-admin/help?module=rbac_h",
    relatedLinks: [{ label: "RBAC role change SOP", href: "/super-admin/help?type=sop&module=rbac_h" }],
  },
  {
    key: "security_p",
    name: "Security / Compliance Center",
    letter: "P",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "owner",
    route: "/super-admin/security",
    docLink: "/super-admin/help?module=security_p",
    relatedLinks: [{ label: "Security incident SOP", href: "/super-admin/help?type=sop&module=security_p" }],
  },
  {
    key: "audit_f",
    name: "Audit Consolidation",
    letter: "F",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "auditor",
    route: "/super-admin/platform/audit",
    docLink: "/super-admin/help?module=audit_f",
    relatedLinks: [{ label: "Audit export SOP", href: "/super-admin/help?type=sop&module=audit_f" }],
  },
  {
    key: "support_g",
    name: "Support Access Hardening",
    letter: "G",
    status: "production_stable",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/platform/support",
    docLink: "/super-admin/help?module=support_g",
    relatedLinks: [{ label: "Support access SOP", href: "/super-admin/help?type=sop&module=support_g" }],
  },
  {
    key: "backup_j",
    name: "Backup / Restore / Disaster Recovery",
    letter: "J",
    status: "production_stable",
    prNumber: null,
    prCommit: "7e01c3e",
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/backups",
    docLink: "/super-admin/help?module=backup_j",
    relatedLinks: [
      { label: "Backup creation SOP", href: "/super-admin/help?type=sop&module=backup_j" },
      { label: "Disaster recovery playbook", href: "/super-admin/help?type=playbook&module=backup_j" },
    ],
  },
  {
    key: "export_k",
    name: "Data Export Center",
    letter: "K",
    status: "production_stable",
    prNumber: null,
    prCommit: "28204b8",
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/exports",
    docLink: "/super-admin/help?module=export_k",
    relatedLinks: [{ label: "Data export approval SOP", href: "/super-admin/help?type=sop&module=export_k" }],
  },
  {
    key: "observability_l",
    name: "Health / Observability",
    letter: "L",
    status: "production_stable",
    prNumber: 138,
    prCommit: "54e765d",
    deployNumber: 92,
    lastSmokeResult: "Pass — post-deploy verified (Deploy #92)",
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/observability",
    docLink: "/super-admin/help?module=observability_l",
    relatedLinks: [{ label: "Site down playbook", href: "/super-admin/help?type=playbook&module=observability_l" }],
  },
  {
    key: "jobs_m",
    name: "Background Jobs Console",
    letter: "M",
    status: "production_stable",
    prNumber: 139,
    prCommit: "7924cfc",
    deployNumber: 93,
    lastSmokeResult: "Pass — 15/15 post-deploy points verified (Deploy #93)",
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/jobs",
    docLink: "/super-admin/help?module=jobs_m",
    relatedLinks: [{ label: "Failed job retry SOP", href: "/super-admin/help?type=sop&module=jobs_m" }],
  },
  {
    key: "communication_o",
    name: "Communication Admin",
    letter: "O",
    status: "production_stable",
    prNumber: 140,
    prCommit: "ae7021b",
    deployNumber: 94,
    lastSmokeResult: "Pass — 18/18 post-deploy points verified (Deploy #94)",
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/communication",
    docLink: "/super-admin/help?module=communication_o",
    relatedLinks: [{ label: "Broadcast SOP", href: "/super-admin/help?type=sop&module=communication_o" }],
  },
  {
    key: "overview_e",
    name: "Platform Overview Dashboard",
    letter: "E",
    status: "production_stable",
    prNumber: 141,
    prCommit: "4815702",
    deployNumber: 95,
    lastSmokeResult: "Pass — 14/14 post-deploy points verified (Deploy #95)",
    lastUpdated: CURATED,
    ownerRole: "owner",
    route: "/super-admin/platform",
    docLink: "/super-admin/help?module=overview_e",
    relatedLinks: [{ label: "Platform Overview", href: "/super-admin/platform" }],
  },
  {
    key: "help_q",
    name: "Help / SOP / Documentation Center",
    letter: "Q",
    status: "in_progress",
    prNumber: null,
    prCommit: null,
    deployNumber: null,
    lastSmokeResult: null,
    lastUpdated: CURATED,
    ownerRole: "technical_admin",
    route: "/super-admin/help",
    docLink: "/super-admin/help",
    relatedLinks: [{ label: "Deployment smoke-test SOP", href: "/super-admin/help?type=sop&module=help_q" }],
  },
];
