import type { Playbook, DocMeta, DocReviewStatus } from "../help.types";

// Section I — emergency playbooks. Curated, read-only incident runbooks. Each
// leads with symptoms and what NOT to do, then safe steps and recovery. Contacts
// are described as roles/processes only — never real people or endpoints.

const meta = (moduleOwner: string, reviewStatus: DocReviewStatus = "reviewed"): DocMeta => ({
  version: "1.0",
  lastUpdatedBy: "Platform Engineering",
  lastUpdated: "2026-07-07",
  reviewedBy: reviewStatus === "reviewed" ? "Platform Owner" : null,
  reviewStatus,
  nextReviewDate: "2026-10-07",
  moduleOwner,
});

export const playbooks: Playbook[] = [
  {
    id: "site-down",
    title: "Site down",
    severity: "critical",
    symptoms: [
      "The platform is unreachable or returns errors for all users.",
      "Health checks are failing across the board.",
    ],
    firstChecks: [
      "Confirm it is platform-wide, not just your session or network.",
      "Check Health / Observability for the failing component.",
      "Check whether a recent deploy coincides with the outage.",
    ],
    whatNotToDo: [
      "Do not trigger a restore as a first reflex — it rarely fixes an outage and risks data.",
      "Do not make multiple large changes at once; you will not know what helped.",
    ],
    safeSteps: [
      "Declare an incident and assemble responders via your on-call process.",
      "If a recent deploy is implicated, prepare to roll back using the rollback SOP.",
      "Restore the failing component (e.g. worker or app) per your infrastructure runbook.",
      "Re-check health and confirm the platform is reachable again.",
    ],
    escalationPath: "Escalate immediately to the platform owner through the on-call channel; nominate one incident lead.",
    relatedModules: ["observability_l", "overview_e", "jobs_m"],
    auditSecurityNotes: "Record the outage timeline and any emergency actions; confirm nothing security-relevant was disabled.",
    recoveryChecklist: [
      "Run the deployment smoke-test.",
      "Confirm Observability is green.",
      "Post a status update and capture follow-ups.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "database-unhealthy",
    title: "Database unhealthy",
    severity: "critical",
    symptoms: [
      "Queries are timing out or erroring.",
      "Health signals show the database degraded or unreachable.",
    ],
    firstChecks: [
      "Check Observability for database health and connection errors.",
      "Confirm whether the whole platform or one function is affected.",
      "Check for a recent migration or deploy that touched the database.",
    ],
    whatNotToDo: [
      "Do not restore over a live database to 'reset' it — that destroys current data.",
      "Do not run ad-hoc destructive queries against production.",
    ],
    safeSteps: [
      "Declare an incident and involve the platform owner.",
      "Stabilise connectivity and resource pressure per the infrastructure runbook.",
      "If a migration is implicated, follow the migration-failed playbook.",
      "Only consider a restore with full preview and owner approval if data is lost.",
    ],
    escalationPath: "Escalate to the platform owner immediately; database recovery is owner-directed.",
    relatedModules: ["observability_l", "backup_j", "overview_e"],
    auditSecurityNotes: "Preserve logs; note any emergency access used and confirm it is revoked afterwards.",
    recoveryChecklist: [
      "Confirm the database is healthy in Observability.",
      "Validate a sample of critical data.",
      "Run the full regression's read-only checks.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "deploy-failed",
    title: "Deploy failed",
    severity: "high",
    symptoms: [
      "A deployment reported failure or left the app unhealthy.",
      "New errors appeared right after a release.",
    ],
    firstChecks: [
      "Confirm the deploy's reported outcome and which stage failed.",
      "Check Observability for new error spikes.",
      "Confirm whether the app is serving at all.",
    ],
    whatNotToDo: [
      "Do not repeatedly redeploy hoping it resolves itself.",
      "Do not skip the smoke-test after any recovery attempt.",
    ],
    safeSteps: [
      "Decide quickly between a forward-fix and a rollback.",
      "If unhealthy, follow the rollback SOP to the previous known-good release.",
      "Take a fresh backup first if data may have changed.",
      "Run the deployment smoke-test after recovery.",
    ],
    escalationPath: "Notify the platform owner; owner approves a production rollback.",
    relatedModules: ["observability_l", "overview_e", "help_q"],
    auditSecurityNotes: "Record the failed deploy and recovery action; note the target release rolled back to.",
    recoveryChecklist: [
      "Smoke-test passes.",
      "Observability green.",
      "Failure symptoms gone.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "migration-failed",
    title: "Migration failed",
    severity: "critical",
    symptoms: [
      "A schema migration errored during deploy.",
      "The app is failing due to a partially applied schema.",
    ],
    firstChecks: [
      "Identify which migration failed and how far it got.",
      "Check whether the database is in a consistent state.",
      "Confirm a recent backup exists from before the migration.",
    ],
    whatNotToDo: [
      "Do not edit an already-applied migration — add a corrective one instead.",
      "Do not blindly retry a destructive migration on partially changed data.",
    ],
    safeSteps: [
      "Involve the platform owner before altering the database.",
      "Assess whether to complete, correct-forward, or restore from the pre-migration backup.",
      "If restoring, follow the restore SOP with preview and approval.",
      "Verify schema consistency before returning to service.",
    ],
    escalationPath: "Escalate to the platform owner; schema recovery decisions are owner-directed.",
    relatedModules: ["backup_j", "observability_l", "overview_e"],
    auditSecurityNotes: "Record the failed migration, decision taken, and any restore performed.",
    recoveryChecklist: [
      "Schema is consistent and the app boots cleanly.",
      "Critical data validates.",
      "Smoke-test passes.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "login-auth-broken",
    title: "Login / auth broken",
    severity: "critical",
    symptoms: [
      "Users cannot sign in, or sessions are being rejected.",
      "Auth-related errors appear across the platform.",
    ],
    firstChecks: [
      "Confirm it affects many users, not one account.",
      "Check Observability and recent deploys for an auth-related change.",
      "Confirm whether second-factor or session handling is the failing part.",
    ],
    whatNotToDo: [
      "Do not disable authentication or 2FA to 'get people in' — that is a security breach.",
      "Do not mass-reset credentials as a shortcut.",
    ],
    safeSteps: [
      "Treat as an incident and involve the platform owner.",
      "If a deploy caused it, roll back via the rollback SOP.",
      "Restore the failing auth component per the infrastructure runbook.",
      "Verify sign-in works for a test account before declaring recovery.",
    ],
    escalationPath: "Escalate to the platform owner immediately; auth changes are owner-directed.",
    relatedModules: ["security_p", "admins_i", "observability_l"],
    auditSecurityNotes: "Confirm no security control was weakened during recovery; review auth logs for anomalies.",
    recoveryChecklist: [
      "Test account signs in with a second factor.",
      "No auth errors in Observability.",
      "Security controls confirmed intact.",
    ],
    meta: meta("owner"),
  },
  {
    id: "last-owner-recovery",
    title: "Last owner recovery",
    severity: "critical",
    symptoms: [
      "No active platform owner can sign in.",
      "Owner-only actions are blocked for everyone.",
    ],
    firstChecks: [
      "Confirm no other owner can access the platform by normal means.",
      "Confirm the identity of whoever is requesting recovery.",
    ],
    whatNotToDo: [
      "Do not create multiple new owners 'just in case'.",
      "Do not skip identity verification under time pressure.",
    ],
    safeSteps: [
      "Follow the emergency owner recovery SOP and its break-glass procedure.",
      "Verify identity rigorously, out of band.",
      "Restore a single owner account and require immediate 2FA enrolment.",
      "Review recent audit activity for anything unexpected during lockout.",
    ],
    escalationPath: "Break-glass authorisation per the operations runbook; owner recovery is the process itself.",
    relatedModules: ["admins_i", "security_p", "audit_f"],
    auditSecurityNotes: "Log the recovery with actor, subject, verification and time; keep the break-glass record.",
    recoveryChecklist: [
      "Exactly one owner recovered.",
      "Fresh second factor enrolled.",
      "Audit reviewed for the lockout window.",
    ],
    meta: meta("owner"),
  },
  {
    id: "payment-gateway-failure",
    title: "Payment gateway failure",
    severity: "high",
    symptoms: [
      "Online payments are failing or not being captured.",
      "Gateway errors appear against invoices.",
    ],
    firstChecks: [
      "Confirm whether a gateway is configured (it is optional).",
      "Check Observability for gateway-related errors.",
      "Confirm the scope — all tenants or specific ones.",
    ],
    whatNotToDo: [
      "Do not store card or gateway secrets in notes, tickets or exports.",
      "Do not mark invoices paid before settlement is confirmed.",
    ],
    safeSteps: [
      "Switch affected tenants to manual payment recording temporarily.",
      "Record payments manually once settlement is confirmed out of band.",
      "Follow the payment-gateway-issue SOP.",
      "Reconcile all manual entries once the gateway recovers.",
    ],
    escalationPath: "Notify the billing owner; involve technical admin for gateway connectivity.",
    relatedModules: ["invoice", "billing_c", "observability_l"],
    auditSecurityNotes: "Log manual payment records with reason; never record secrets in the trail.",
    recoveryChecklist: [
      "Gateway healthy or manual process in place.",
      "Manual entries reconciled.",
      "Invoice states correct.",
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "smtp-email-failure",
    title: "SMTP / email failure",
    severity: "medium",
    symptoms: [
      "Outbound emails are not arriving.",
      "Email-based notifications are missing.",
    ],
    firstChecks: [
      "Confirm whether a mail service is configured at all (it is optional).",
      "Check Observability and job history for delivery errors.",
      "Confirm whether in-app delivery still works.",
    ],
    whatNotToDo: [
      "Do not put mail credentials into documentation, tickets or exports.",
      "Do not assume users saw a message that only failed over email.",
    ],
    safeSteps: [
      "Fall back to in-app delivery for anything urgent.",
      "Restore or reconfigure the mail service per the infrastructure runbook.",
      "Re-send critical notifications once email recovers.",
      "Confirm delivery with a test message.",
    ],
    escalationPath: "Notify technical admin; escalate to the owner if critical communications are blocked.",
    relatedModules: ["communication_o", "jobs_m", "observability_l"],
    auditSecurityNotes: "Log any re-sends; never record mail credentials anywhere in the trail.",
    recoveryChecklist: [
      "Test email delivers.",
      "Critical notifications re-sent.",
      "No delivery errors in jobs.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "backup-failure",
    title: "Backup failure",
    severity: "high",
    symptoms: [
      "A scheduled or manual backup did not complete.",
      "No recent successful backup is present.",
    ],
    firstChecks: [
      "Check the Backup / Restore list for the last successful backup.",
      "Check Observability and jobs for the failure reason.",
      "Confirm whether the background worker is running.",
    ],
    whatNotToDo: [
      "Do not proceed with risky changes while there is no recent good backup.",
      "Do not assume a started backup succeeded — verify completion.",
    ],
    safeSteps: [
      "Resolve the underlying cause (worker, storage capacity, permissions).",
      "Trigger a fresh backup via the backup-creation SOP and confirm success.",
      "Copy it to a secure secondary location per DR policy.",
      "Restore the backup schedule to normal.",
    ],
    escalationPath: "Notify technical admin; escalate to owner if no valid backup exists.",
    relatedModules: ["backup_j", "jobs_m", "observability_l"],
    auditSecurityNotes: "Log the failure and the successful re-run; note where the offsite copy was placed (by role, not path).",
    recoveryChecklist: [
      "A new backup completed successfully.",
      "Offsite copy made.",
      "Schedule healthy again.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "restore-request",
    title: "Restore request",
    severity: "high",
    symptoms: [
      "A restore has been requested to recover lost or corrupted data.",
    ],
    firstChecks: [
      "Confirm exactly what data is lost and the time it was last good.",
      "Identify the closest known-good backup before the incident.",
      "Confirm a restore is truly necessary versus a targeted fix.",
    ],
    whatNotToDo: [
      "Do not restore against real data without a preview and owner approval.",
      "Do not choose a backup after the incident — it will not contain the lost data.",
    ],
    safeSteps: [
      "Run the restore preview and review the exact impact.",
      "Confirm the target and scope with a second person.",
      "Obtain explicit owner approval, then follow the restore SOP.",
      "Run post-restore smoke tests.",
    ],
    escalationPath: "Owner approval is mandatory before executing any restore.",
    relatedModules: ["backup_j", "audit_f", "help_q"],
    auditSecurityNotes: "Log preview, approval and execution; note who approved and the backup used.",
    recoveryChecklist: [
      "Preview reviewed and approved.",
      "Restore executed on the correct target.",
      "Post-restore smoke tests pass.",
    ],
    meta: meta("owner"),
  },
  {
    id: "security-incident",
    title: "Security incident",
    severity: "critical",
    symptoms: [
      "Signs of compromise: unexpected access, anomalies, or abuse.",
      "An admin or tenant reports suspicious activity.",
    ],
    firstChecks: [
      "Assess scope and severity before acting.",
      "Review the Security Center and Audit Console for the activity.",
      "Identify affected accounts, tenants and data.",
    ],
    whatNotToDo: [
      "Do not tip off a suspected malicious actor before containment.",
      "Do not destroy or alter evidence while investigating.",
      "Do not weaken security controls to speed up work.",
    ],
    safeSteps: [
      "Contain: revoke suspicious sessions and tighten affected access.",
      "Preserve evidence — export relevant audit records early.",
      "Follow the security-incident-response SOP.",
      "Remediate the root cause and document a timeline.",
    ],
    escalationPath: "Escalate to the platform owner immediately; major containment is owner-directed.",
    relatedModules: ["security_p", "audit_f", "support_g"],
    auditSecurityNotes: "This is the core of the response — capture every containment action and evidence export with time and actor.",
    recoveryChecklist: [
      "Malicious access confirmed revoked.",
      "Root cause remediated.",
      "Timeline and follow-ups recorded.",
    ],
    meta: meta("owner"),
  },
  {
    id: "data-export-incident",
    title: "Data export incident",
    severity: "high",
    symptoms: [
      "A data export was produced or delivered in a way that may expose sensitive data.",
      "An export scope or recipient looks wrong.",
    ],
    firstChecks: [
      "Identify the export, its scope and where it was delivered.",
      "Check the Audit Console for who created and delivered it.",
      "Assess what sensitive data was included.",
    ],
    whatNotToDo: [
      "Do not create further copies of the exposed export.",
      "Do not delete audit evidence of the export.",
    ],
    safeSteps: [
      "Contain distribution — revoke access to the delivered file where possible.",
      "Treat as a potential security incident if sensitive data was exposed.",
      "Follow the data-export-approval SOP for any corrective re-export.",
      "Document the scope, recipients and remediation.",
    ],
    escalationPath: "Notify the platform owner; involve the auditor for compliance impact.",
    relatedModules: ["export_k", "audit_f", "security_p"],
    auditSecurityNotes: "Preserve the export's audit trail; log all containment actions.",
    recoveryChecklist: [
      "Distribution contained.",
      "Compliance impact assessed.",
      "Corrective process documented.",
    ],
    meta: meta("auditor"),
  },
  {
    id: "failed-jobs-spike",
    title: "Failed jobs spike",
    severity: "high",
    symptoms: [
      "A sudden surge of failed or stuck background jobs.",
      "Scheduled work is backing up.",
    ],
    firstChecks: [
      "Open Background Jobs and identify the common failure pattern.",
      "Confirm whether the background worker is running.",
      "Check Observability for resource pressure or dependency errors.",
    ],
    whatNotToDo: [
      "Do not mass-retry blindly — some jobs are unsafe to run twice.",
      "Do not ignore a stopped worker; retries will not help if it is down.",
    ],
    safeSteps: [
      "If the worker is down, restore it first (jobs depend on it).",
      "Fix the shared root cause (dependency, resource, or data issue).",
      "Retry safe, idempotent jobs via the failed-job-retry SOP.",
      "Confirm the backlog drains.",
    ],
    escalationPath: "Notify technical admin; escalate to owner if critical jobs remain blocked.",
    relatedModules: ["jobs_m", "observability_l", "overview_e"],
    auditSecurityNotes: "Log retries and any bulk action taken with the job references involved.",
    recoveryChecklist: [
      "Worker healthy.",
      "Root cause fixed.",
      "Job backlog cleared.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "storage-full",
    title: "Storage full / near full",
    severity: "high",
    symptoms: [
      "Disk or storage capacity is exhausted or close to it.",
      "Writes, backups or jobs are failing due to space.",
    ],
    firstChecks: [
      "Check Observability for storage-capacity signals.",
      "Confirm what is consuming space (backups, logs, exports).",
      "Confirm whether backups or the worker have already failed.",
    ],
    whatNotToDo: [
      "Do not delete backups or audit data to reclaim space.",
      "Do not remove files you cannot positively identify as safe.",
    ],
    safeSteps: [
      "Reclaim space by clearing clearly-safe, non-critical artifacts per the runbook.",
      "Move older backups to secure secondary storage rather than deleting.",
      "Increase capacity where the infrastructure allows.",
      "Re-run any backup or job that failed due to space.",
    ],
    escalationPath: "Notify technical admin; escalate to owner before removing anything sensitive.",
    relatedModules: ["observability_l", "backup_j", "jobs_m"],
    auditSecurityNotes: "Never delete audit or backup data to free space; log what was cleared and why.",
    recoveryChecklist: [
      "Adequate free space restored.",
      "Failed backups/jobs re-run.",
      "No critical data removed.",
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "tenant-mistakenly-suspended",
    title: "Tenant mistakenly suspended",
    severity: "high",
    symptoms: [
      "A tenant reports they are locked out unexpectedly.",
      "A suspension was applied to the wrong tenant.",
    ],
    firstChecks: [
      "Confirm the tenant's current status in the Tenants module.",
      "Check the Audit Console for who suspended it and why.",
      "Confirm the correct intended tenant.",
    ],
    whatNotToDo: [
      "Do not make further tenant changes before confirming the facts.",
      "Do not delete the audit trail of the mistaken action.",
    ],
    safeSteps: [
      "Reactivate the tenant that was wrongly suspended.",
      "Verify all users in that tenant can sign in again.",
      "If another tenant should have been suspended, action it correctly.",
      "Communicate and apologise to the affected tenant.",
    ],
    escalationPath: "Notify the platform owner of the error; follow the tenant suspension/reactivation SOP.",
    relatedModules: ["tenant", "audit_f", "overview_e"],
    auditSecurityNotes: "Log the correction; the original mistaken suspension remains in the trail for transparency.",
    recoveryChecklist: [
      "Correct tenant reactivated.",
      "Users confirmed back in.",
      "Error communicated and recorded.",
    ],
    meta: meta("owner"),
  },
  {
    id: "invoice-payment-issue",
    title: "Invoice / payment issue",
    severity: "medium",
    symptoms: [
      "An invoice is wrong, duplicated, or a payment is mis-recorded.",
      "A tenant disputes an invoice or payment status.",
    ],
    firstChecks: [
      "Open the invoice and review its details and history.",
      "Check the Audit Console for how it was created or changed.",
      "Confirm the true billing intent with finance.",
    ],
    whatNotToDo: [
      "Do not void an invoice to resolve a dispute — handle disputes through billing.",
      "Do not mark an invoice paid before settlement is confirmed.",
    ],
    safeSteps: [
      "For a genuine error, void it with a recorded reason and re-issue correctly.",
      "Follow the invoice-issue-void SOP.",
      "Reconcile against finance records.",
      "Communicate the resolution to the tenant.",
    ],
    escalationPath: "Notify the billing owner; escalate above your void threshold as required.",
    relatedModules: ["invoice", "subscriptions_d", "audit_f"],
    auditSecurityNotes: "Log the void/re-issue with reasons; keep the full history for reconciliation.",
    recoveryChecklist: [
      "Invoice state correct.",
      "Payment reconciled.",
      "Tenant informed.",
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "support-access-misuse-concern",
    title: "Support access misuse concern",
    severity: "high",
    symptoms: [
      "A support-access grant looks over-broad, left open, or used without cause.",
      "A tenant queries why staff accessed their data.",
    ],
    firstChecks: [
      "Review the grant's scope, duration and status in Support Access.",
      "Check the Audit Console for what was accessed during the grant.",
      "Confirm whether a legitimate reason and consent existed.",
    ],
    whatNotToDo: [
      "Do not delete the grant's audit trail.",
      "Do not extend or reissue the grant while the concern is open.",
    ],
    safeSteps: [
      "Revoke any still-active grant immediately.",
      "If misuse is likely, treat it as a security incident.",
      "Gather evidence via an audit export.",
      "Document findings and remediate the process gap.",
    ],
    escalationPath: "Escalate to the platform owner; involve the auditor for compliance review.",
    relatedModules: ["support_g", "audit_f", "security_p"],
    auditSecurityNotes: "Preserve all grant and access records; log the revocation and investigation.",
    recoveryChecklist: [
      "Active grant revoked.",
      "Access reviewed against a valid reason.",
      "Process gap remediated.",
    ],
    meta: meta("owner"),
  },
];
