// Super Admin Q — curated Release Notes (Section G).
//
// CURATED / manual release notes for the shipped Super-Admin platform modules.
// Ref fields (prNumber / commit / deployNumber) are ONLY the REAL confirmed
// value and are `null` when not known — NEVER fabricated. No secrets, tokens,
// or private logs are ever included.

import type { ReleaseNote } from "../help.types";

export const releaseNotes: ReleaseNote[] = [
  {
    id: "e-platform-overview",
    title: "Super Admin E — Platform Overview Dashboard",
    module: "overview_e",
    prNumber: 141,
    commit: "4815702",
    deployNumber: 95,
    date: "2026-07-07",
    summary:
      "Read-only executive command center aggregating the live module summaries into KPI cards, trends, needs-attention, cross-module status, quick actions and a masked/audited snapshot export.",
    changes: [
      "Executive KPI cards (tenant / subscription / billing / security / operations) each with a real drilldown.",
      "Inline-SVG trend sparklines from real timestamps only; empty series show a 'trend begins from collected data' note.",
      "Prioritized Needs-Attention panel and cross-module status cards.",
      "RBAC-aware quick actions and a masked, audited CSV/JSON export.",
    ],
    migrationSummary: "0103 — additive: two perms (overview:read, overview:export). No tables/indexes.",
    safetyNotes: "Read-only aggregation; only write is the export audit row. Server-side RBAC hides sections with no count leak.",
    smokeResult: "Pass — 14/14 post-deploy points verified.",
    knownLimitations: "Saved dashboard views not implemented; trend history begins at each module's data-collection start.",
    rollbackNote: "Code auto-rolls back on failed health check; migration is additive and safe to leave in place.",
  },
  {
    id: "o-communication-admin",
    title: "Super Admin O — Communication Admin",
    module: "communication_o",
    prNumber: 140,
    commit: "ae7021b",
    deployNumber: 94,
    date: "2026-07-07",
    summary:
      "Platform communication center: email templates, unified delivery log, broadcasts and notification governance.",
    changes: [
      "Email templates with versioning and built-in seeds.",
      "Unified email delivery log (legacy invoice emails read-only source).",
      "Broadcast send and email delivery retry via the background worker.",
      "Per-route comm:* RBAC and masked delivery metadata (never message bodies).",
    ],
    migrationSummary: "0102 — communication admin tables (templates, versions, deliveries, broadcasts, settings).",
    safetyNotes: "Delivery logging stores subject metadata only, masked; never message bodies.",
    smokeResult: "Pass — 18/18 post-deploy points verified.",
    knownLimitations: "Full chat / SMS / marketing automation is intentionally out of scope.",
    rollbackNote: "Auto-rollback on failed health check.",
  },
  {
    id: "m-background-jobs",
    title: "Super Admin M — Background Jobs Console",
    module: "jobs_m",
    prNumber: 139,
    commit: "7924cfc",
    deployNumber: 93,
    date: "2026-07-06",
    summary:
      "Background jobs console: queue governance, workers, scheduler, dead-letter queue and alerts.",
    changes: [
      "Job attempts and worker heartbeats instrumentation.",
      "Dead-letter queue with move/retry.",
      "Queue depth, worker health and failure alerts surfaced to the console.",
    ],
    migrationSummary: "0101 — job_attempts, worker_heartbeats; jobs.status widened (+dead_letter).",
    safetyNotes: "Worker instrumentation is try/catch-guarded; no destructive DDL.",
    smokeResult: "Pass — 15/15 post-deploy points verified.",
    knownLimitations: "Scheduled runs depend on the background worker being enabled.",
    rollbackNote: "Auto-rollback on failed health check.",
  },
  {
    id: "l-health-observability",
    title: "Super Admin L — Health / Observability",
    module: "observability_l",
    prNumber: 138,
    commit: "54e765d",
    deployNumber: 92,
    date: "2026-07-06",
    summary:
      "Health & observability center: incidents, alerts, service-health history, error events and performance.",
    changes: [
      "Incidents and alert-rule management.",
      "Service-health history and error-event capture.",
      "Platform health dashboard consumed by the Platform Overview.",
    ],
    migrationSummary: "0100 — incidents, alerts, service_health_history, error_events.",
    safetyNotes: "Additive schema; read-heavy with cooldown-gated health checks.",
    smokeResult: "Pass — post-deploy verified.",
    knownLimitations: "Alert-rule notifications depend on communication/worker availability.",
    rollbackNote: "Auto-rollback on failed health check.",
  },
  {
    id: "k-data-export-center",
    title: "Super Admin K — Data Export Center",
    module: "export_k",
    prNumber: null,
    commit: "28204b8",
    deployNumber: null,
    date: "2026-07-05",
    summary: "Platform data export center: export artifacts, scheduling, and governance/approvals.",
    changes: [
      "Export artifacts with governance and approval flow.",
      "Scheduled and on-demand exports.",
    ],
    migrationSummary: "0099 — data export center tables.",
    safetyNotes: "Sensitive exports gated by approval; masked where applicable.",
    smokeResult: null,
    knownLimitations: "Large exports may be capped for safety; see the limitations register.",
    rollbackNote: null,
  },
  {
    id: "j-backup-restore-dr",
    title: "Super Admin J — Backup / Restore / Disaster Recovery",
    module: "backup_j",
    prNumber: null,
    commit: "7e01c3e",
    deployNumber: null,
    date: "2026-07-05",
    summary: "Backup, restore, offsite storage, verification and disaster-recovery hardening.",
    changes: [
      "Backup creation and verification.",
      "Restore preview / request / approval flow.",
      "Offsite storage and DR procedures.",
    ],
    migrationSummary: "0098 — backup / DR hardening tables.",
    safetyNotes: "Restore is approval-gated and never destructive without confirmation.",
    smokeResult: null,
    knownLimitations: "Offsite encryption depends on optional storage configuration.",
    rollbackNote: null,
  },
  {
    id: "n-settings-consolidation",
    title: "Super Admin N — Settings Consolidation",
    module: "settings_n",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-04",
    summary: "Consolidated platform settings and feature flags with a maintenance/announcement banner.",
    changes: ["Platform settings + feature flags.", "Maintenance-mode and announcement banner."],
    migrationSummary: "Additive platform-settings tables (see module history).",
    safetyNotes: "Settings are the source of truth for maintenance mode; changes are audited.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "c-saas-billing",
    title: "Super Admin C — SaaS Billing / Packages / Coupons / GST",
    module: "billing_c",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-03",
    summary: "SaaS billing: subscription packages, coupons, GST, payment and plan limits.",
    changes: ["Package versions and add-ons.", "Coupons, GST readiness and plan limits."],
    migrationSummary: "Additive billing/package tables (see module history).",
    safetyNotes: "Money handled as paise-integers; gateway secrets never exposed.",
    smokeResult: null,
    knownLimitations: "Payment gateway is an optional integration and degrades gracefully when unconfigured.",
    rollbackNote: null,
  },
  {
    id: "d-subscription-management",
    title: "Super Admin D — Subscription Management",
    module: "subscriptions_d",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-03",
    summary: "Tenant subscription lifecycle: renewals, grace, expiry and cancellation.",
    changes: ["Subscription lifecycle management.", "Renewal, grace and expiry handling."],
    migrationSummary: "Additive subscription tables (see module history).",
    safetyNotes: "Lifecycle transitions are audited.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "i-platform-admin-users",
    title: "Super Admin I — Platform Admin User Management",
    module: "admins_i",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-02",
    summary: "Platform admin user management: invite, disable, and platform sub-roles.",
    changes: ["Invite / disable platform admins.", "Platform sub-role assignment."],
    migrationSummary: "Additive platform-admin tables (see module history).",
    safetyNotes: "Owner-safety guards prevent locking out the last owner.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "h-rbac-enforcement",
    title: "Super Admin H — RBAC / Permission Enforcement",
    module: "rbac_h",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-02",
    summary: "Role/permission model and server-side enforcement for platform sub-roles.",
    changes: ["Role → permission catalogue.", "Server-side requirePermission enforcement with caching."],
    migrationSummary: "Additive rbac_roles / role_permissions (see module history).",
    safetyNotes: "Owner / unclassified super_admin retain full access; enforcement is server-side.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "p-security-center",
    title: "Super Admin P — Security / Compliance Center",
    module: "security_p",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-04",
    summary: "Security & compliance center: high-risk activity, login history, 2FA compliance and alerts.",
    changes: ["Security dashboard and alerts.", "Login history and 2FA compliance."],
    migrationSummary: "0094 — security center tables.",
    safetyNotes: "Security events are masked; no secrets rendered.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "f-audit-consolidation",
    title: "Super Admin F — Audit Consolidation",
    module: "audit_f",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-04",
    summary: "Consolidated platform audit console with filters, detail and masked export.",
    changes: ["Unified platform_audit_log console.", "Filters, detail drawer and masked export."],
    migrationSummary: "0095 — audit consolidation.",
    safetyNotes: "Audit detail is masked; export never emits secrets.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "g-support-access",
    title: "Super Admin G — Support Access Hardening",
    module: "support_g",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-04",
    summary: "Time-boxed, audited support-access sessions into tenant contexts.",
    changes: ["Support-access session request / grant / expiry.", "Full audit of support access."],
    migrationSummary: "0096 / 0097 — support access.",
    safetyNotes: "Support sessions are time-boxed and fully audited.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "invoice-module",
    title: "Invoice Module",
    module: "invoice",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-01",
    summary: "SaaS invoicing: issue, void, credit/debit notes, GST fields, delivery log and reports.",
    changes: ["Editable drafts, void with reason, credit/debit notes.", "GST fields, email delivery log, reports + export."],
    migrationSummary: "Additive invoice tables (see module history).",
    safetyNotes: "Money as paise-integers; email log masked.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "tenant-module",
    title: "Tenant / Institution Module",
    module: "tenant",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-01",
    summary: "Institution management: list, detail, create/edit, soft-archive and recent activity.",
    changes: ["Institutions list with search/filter/export.", "Detail, create/edit and soft-archive."],
    migrationSummary: "Additive institution tables (see module history).",
    safetyNotes: "Soft-archive only — no hard delete.",
    smokeResult: null,
    knownLimitations: null,
    rollbackNote: null,
  },
  {
    id: "q-help-center",
    title: "Super Admin Q — Help / SOP / Documentation Center",
    module: "help_q",
    prNumber: null,
    commit: null,
    deployNumber: null,
    date: "2026-07-07",
    summary:
      "In-app help center: help articles, SOP library, smoke-test checklists, known-limitations register, release notes, admin onboarding, emergency playbooks and a curated module-status register.",
    changes: [
      "Read-only curated documentation surface with search + filters.",
      "Curated module-status register (real refs only, null where unconfirmed).",
      "Masked, audited snapshot export (help.exported).",
    ],
    migrationSummary: "0104 — additive: two perms (help:read, help:export). No tables/indexes.",
    safetyNotes: "Read-only aggregation; only write is the export audit row. A build-time test scans all bundled docs for secrets.",
    smokeResult: null,
    knownLimitations: "Docs are curated-in-code (not editable in-app); editable/persisted docs are a documented future enhancement.",
    rollbackNote: "Additive migration; safe to leave in place on rollback.",
  },
];
