import type { Sop, DocMeta, DocReviewStatus } from "../help.types";

// Section D — standard operating procedures. Curated, read-only, step-by-step
// runbooks for planned platform actions. Steps are plain strings; every SOP
// states its safety warnings, approval need, audit expectation and smoke test.

const meta = (moduleOwner: string, reviewStatus: DocReviewStatus = "reviewed"): DocMeta => ({
  version: "1.0",
  lastUpdatedBy: "Platform Engineering",
  lastUpdated: "2026-07-07",
  reviewedBy: reviewStatus === "reviewed" ? "Platform Owner" : null,
  reviewStatus,
  nextReviewDate: "2026-10-07",
  moduleOwner,
});

export const sops: Sop[] = [
  {
    id: "new-tenant-onboarding",
    title: "New tenant onboarding",
    purpose: "Create a new institution and bring it to a ready-to-use state.",
    whenToUse: "When a new school or college is being added to the platform.",
    requiredRole: "Owner / Super Admin or Technical Admin",
    steps: [
      "Confirm the institution name and correct type (school vs college) with the requester.",
      "Create the tenant record with the confirmed name and type.",
      "Attach an appropriate billing package and start a subscription.",
      "Create the tenant's first administrator account.",
      "Sign-in check as (or with) the tenant admin to confirm the correct mode loads.",
      "Record the onboarding request reference in your operations log.",
    ],
    safetyWarnings: [
      "Institution type is structural and hard to change later — get it right at creation.",
      "Do not reuse another tenant's details; each tenant must be distinct.",
    ],
    approvalRequired: null,
    auditExpectation: "Tenant creation, package/subscription assignment and admin creation are all recorded in the audit log with your identity.",
    smokeTestCheck: "The new tenant appears in the Tenants list and its first admin can sign in and see the expected school/college mode.",
    relatedLinks: [
      { label: "Tenants", href: "/super-admin/platform/tenants" },
      { label: "SaaS Billing", href: "/super-admin/packages" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "tenant-suspension-reactivation",
    title: "Tenant suspension and reactivation",
    purpose: "Block or restore a tenant's access to the platform.",
    whenToUse: "For non-payment, policy breach, offboarding, or restoring a wrongly suspended tenant.",
    requiredRole: "Owner / Super Admin",
    steps: [
      "Verify you have the exact correct tenant by name and identifier.",
      "Confirm the documented reason and that suspension is the right response.",
      "Suspend the tenant and note the reason.",
      "Communicate the change to the tenant through the agreed channel.",
      "To reactivate, confirm the underlying issue is resolved, then reactivate.",
      "Verify the resulting access state matches intent.",
    ],
    safetyWarnings: [
      "Suspension blocks every user in the tenant at once — high impact.",
      "Double-check the tenant identity; suspending the wrong tenant is an incident.",
    ],
    approvalRequired: "Owner sign-off for suspension of an active paying tenant.",
    auditExpectation: "Suspension and reactivation events are logged with actor, tenant and reason.",
    smokeTestCheck: "Tenant status shows suspended (users blocked) or active (users can sign in) as intended.",
    relatedLinks: [
      { label: "Tenants", href: "/super-admin/platform/tenants" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("owner"),
  },
  {
    id: "invoice-issue-void",
    title: "Invoice issue and void",
    purpose: "Raise an invoice for a tenant or void one raised in error.",
    whenToUse: "When billing a tenant, or correcting an invoice created incorrectly.",
    requiredRole: "Billing Admin",
    steps: [
      "Confirm tenant, amount, billing period and line items.",
      "Issue the invoice and verify it appears with correct details.",
      "To void, confirm the invoice was genuinely raised in error.",
      "Void the invoice and record the reason.",
      "Notify finance so records stay reconciled.",
    ],
    safetyWarnings: [
      "Voiding is a permanent state change, not a delete.",
      "Never void to resolve a payment dispute — handle disputes through billing.",
    ],
    approvalRequired: "Billing owner approval to void an invoice above your threshold.",
    auditExpectation: "Issue and void actions are logged with actor, tenant, amount and reason.",
    smokeTestCheck: "Issued invoice shows correct details; voided invoice shows a voided state with a reason.",
    relatedLinks: [
      { label: "Invoices", href: "/super-admin/invoices" },
      { label: "SaaS Billing", href: "/super-admin/packages" },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "subscription-renewal",
    title: "Subscription renewal",
    purpose: "Extend a tenant's subscription so their access continues.",
    whenToUse: "Before a subscription's expiry date, or to correct a lapsed one.",
    requiredRole: "Billing Admin",
    steps: [
      "Open the tenant's subscription and confirm the current package and period.",
      "Confirm the renewal package and new period with the requester.",
      "Apply the renewal.",
      "Verify the new expiry date and package are correct.",
      "Inform the tenant that their subscription is renewed.",
    ],
    safetyWarnings: [
      "A lapsed subscription can restrict tenant access — renew before expiry.",
      "Renewing onto the wrong package changes entitlements; confirm first.",
    ],
    approvalRequired: null,
    auditExpectation: "Renewal is logged with actor, tenant, package and new period.",
    smokeTestCheck: "Subscription shows the extended period and correct package; tenant retains access.",
    relatedLinks: [
      { label: "Subscriptions", href: "/super-admin/subscriptions" },
      { label: "SaaS Billing", href: "/super-admin/packages" },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "payment-gateway-issue",
    title: "Payment gateway issue handling",
    purpose: "Respond when online payment collection is failing or unavailable.",
    whenToUse: "When payments are not being captured, or no gateway is configured.",
    requiredRole: "Billing Admin with Technical Admin support",
    steps: [
      "Confirm whether a payment gateway is configured at all (it is optional).",
      "Check Observability for related errors or degraded signals.",
      "If the gateway is down, switch affected tenants to manual payment recording temporarily.",
      "Record payments manually once settlement is confirmed out of band.",
      "Reconcile all manual entries when the gateway recovers.",
    ],
    safetyWarnings: [
      "Never store card or gateway credentials in notes, tickets or exports.",
      "Do not mark an invoice paid before settlement is confirmed.",
    ],
    approvalRequired: null,
    auditExpectation: "Manual payment records and status changes are logged with actor and reason.",
    smokeTestCheck: "A test payment (or a manually recorded one) reflects correctly against the invoice.",
    relatedLinks: [
      { label: "Invoices", href: "/super-admin/invoices" },
      { label: "Health / Observability", href: "/super-admin/observability" },
    ],
    meta: meta("billing_admin"),
  },
  {
    id: "rbac-role-change",
    title: "RBAC role change",
    purpose: "Change a platform admin's role or permissions.",
    whenToUse: "On joining, role change, or removing access that is no longer needed.",
    requiredRole: "Owner / Super Admin",
    steps: [
      "Confirm the person and the exact access they should have.",
      "Select the least-privilege role that meets the need.",
      "Apply the role change.",
      "Ask the person to re-check what they can and cannot do.",
      "Record why the change was made.",
    ],
    safetyWarnings: [
      "Role changes take effect immediately.",
      "Avoid granting owner-level access unless genuinely required.",
    ],
    approvalRequired: "Owner approval to grant owner-level or broad administrative roles.",
    auditExpectation: "Role and permission changes are logged with actor, subject and new role.",
    smokeTestCheck: "The admin can perform newly granted actions and can no longer perform revoked ones.",
    relatedLinks: [
      { label: "RBAC", href: "/super-admin/rbac" },
      { label: "Platform Admin Users", href: "/super-admin/admins" },
    ],
    meta: meta("owner"),
  },
  {
    id: "platform-admin-invite-disable",
    title: "Platform admin invite and disable",
    purpose: "Add a new platform administrator or disable an existing one.",
    whenToUse: "When onboarding platform staff or offboarding a leaver.",
    requiredRole: "Owner / Super Admin",
    steps: [
      "Confirm the person should have platform-level access at all.",
      "Invite them with their own individual account and an appropriate role.",
      "Confirm they complete sign-in and enrol a second factor.",
      "To offboard, disable the account promptly on their last day.",
      "Verify a disabled account can no longer sign in.",
    ],
    safetyWarnings: [
      "Never create shared accounts — accountability depends on individual logins.",
      "Disable leavers promptly; lingering access is a security risk.",
    ],
    approvalRequired: "Owner approval to invite a new platform administrator.",
    auditExpectation: "Invite, enable and disable events are logged with actor and subject.",
    smokeTestCheck: "New admin can sign in with their role; disabled admin is blocked.",
    relatedLinks: [
      { label: "Platform Admin Users", href: "/super-admin/admins" },
      { label: "RBAC", href: "/super-admin/rbac" },
    ],
    meta: meta("owner"),
  },
  {
    id: "two-factor-reset",
    title: "Two-factor (2FA) reset",
    purpose: "Restore access for an admin locked out of their second factor.",
    whenToUse: "When an admin has lost their authenticator and cannot sign in.",
    requiredRole: "Owner / Super Admin or Technical Admin",
    steps: [
      "Verify the requester's identity out of band — never on their word alone.",
      "Confirm the account and that a reset is warranted.",
      "Reset the second factor for that account only.",
      "Have the admin immediately enrol a new authenticator.",
      "Confirm they can sign in with the new factor.",
    ],
    safetyWarnings: [
      "A 2FA reset is a security-sensitive action — identity verification is mandatory.",
      "Reset only the intended account; never batch-reset factors.",
    ],
    approvalRequired: "Second approver for resetting another platform admin's 2FA.",
    auditExpectation: "The reset is logged with actor, subject, time and verification note.",
    smokeTestCheck: "The affected admin signs in with a freshly enrolled second factor.",
    relatedLinks: [
      { label: "Security Center", href: "/super-admin/security" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "support-access-grant",
    title: "Support access grant",
    purpose: "Give platform staff controlled access into a tenant to assist them.",
    whenToUse: "When helping a tenant requires acting within their space.",
    requiredRole: "Owner / Super Admin or Technical Admin",
    steps: [
      "Confirm the tenant and the specific task requiring access.",
      "Start a grant scoped to that tenant with the narrowest scope.",
      "Set the shortest practical duration.",
      "Perform only the agreed work.",
      "Revoke the grant as soon as the work is complete.",
    ],
    safetyWarnings: [
      "Over-broad or open-ended grants are the main risk — keep them tight.",
      "Do not use support access to browse tenant data without a reason.",
    ],
    approvalRequired: "Tenant consent per your support policy before accessing their data.",
    auditExpectation: "Grant start, scope, actions and revocation are all logged.",
    smokeTestCheck: "The grant appears active during work and shows revoked immediately after.",
    relatedLinks: [
      { label: "Support Access", href: "/super-admin/platform/support" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "backup-creation",
    title: "Backup creation",
    purpose: "Produce a verified backup of platform data.",
    whenToUse: "On schedule, and before any risky change or deploy.",
    requiredRole: "Technical Admin",
    steps: [
      "Open the Backup / Restore module.",
      "Trigger a new backup.",
      "Wait for it to complete and confirm success, not just that it started.",
      "Note the backup's timestamp/identifier for reference.",
      "Copy it to a secure secondary location per your DR policy.",
    ],
    safetyWarnings: [
      "A started backup is not a finished backup — always confirm completion.",
      "Offsite copy and encryption are not automatic; handle them per policy.",
    ],
    approvalRequired: null,
    auditExpectation: "Backup creation is logged with actor and outcome.",
    smokeTestCheck: "The new backup appears in the list with a success state and recent timestamp.",
    relatedLinks: [
      { label: "Backup / Restore", href: "/super-admin/backups" },
      { label: "Health / Observability", href: "/super-admin/observability" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "restore-preview-request-approval",
    title: "Restore preview, request and approval",
    purpose: "Safely restore platform data from a backup.",
    whenToUse: "Only when data must be recovered from a known-good backup.",
    requiredRole: "Owner / Super Admin with Technical Admin",
    steps: [
      "Identify the closest known-good backup before the incident.",
      "Run the restore preview and review exactly what it will change.",
      "Confirm the target and scope with a second person.",
      "Obtain explicit owner approval to proceed.",
      "Execute the restore, then run the relevant smoke-test checklist.",
    ],
    safetyWarnings: [
      "Restore can overwrite current data — it is among the most destructive actions.",
      "Never restore against real data without a preview and approval.",
      "Point-in-time restore is unavailable; data after the backup is not recovered.",
    ],
    approvalRequired: "Explicit platform owner approval, recorded before execution.",
    auditExpectation: "Preview, approval and restore execution are all logged with actor and target.",
    smokeTestCheck: "Post-restore smoke tests pass and the recovered data matches expectations.",
    relatedLinks: [
      { label: "Backup / Restore", href: "/super-admin/backups" },
      { label: "Help / SOP Center", href: "/super-admin/help" },
    ],
    meta: meta("owner"),
  },
  {
    id: "data-export-approval",
    title: "Data export approval",
    purpose: "Produce and deliver a data export under approval and audit.",
    whenToUse: "For tenant data requests or compliance evidence.",
    requiredRole: "Auditor or Technical Admin",
    steps: [
      "Define the export scope precisely (tenant, entities, date range).",
      "Obtain approval for sensitive scopes.",
      "Generate the export, chunking large volumes by date or tenant.",
      "Deliver only through an approved, secure channel.",
      "Confirm request and delivery are recorded.",
    ],
    safetyWarnings: [
      "Exports can contain sensitive data — never deliver via ad-hoc channels.",
      "Large exports are capped; do not force a single oversized run.",
    ],
    approvalRequired: "Approver sign-off for exports containing sensitive personal data.",
    auditExpectation: "Export creation, scope and delivery are logged with actor.",
    smokeTestCheck: "A small test export produces the expected file and is logged.",
    relatedLinks: [
      { label: "Data Export Center", href: "/super-admin/exports" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("auditor"),
  },
  {
    id: "audit-export",
    title: "Audit export",
    purpose: "Export audit-trail evidence for an investigation or compliance.",
    whenToUse: "When durable, shareable proof of platform activity is needed.",
    requiredRole: "Auditor (read-only)",
    steps: [
      "Filter the audit trail to the relevant actor, module, action and dates.",
      "Confirm the filter captures exactly the evidence required.",
      "Export the filtered audit records.",
      "Deliver through an approved channel and note the purpose.",
      "Retain a reference so the export itself is accounted for.",
    ],
    safetyWarnings: [
      "Audit exports may contain sensitive activity data — handle accordingly.",
      "Never alter exported audit content; it must remain faithful.",
    ],
    approvalRequired: null,
    auditExpectation: "The audit export action is itself logged with actor and scope.",
    smokeTestCheck: "The export contains the expected events for the chosen filter.",
    relatedLinks: [
      { label: "Audit Console", href: "/super-admin/platform/audit" },
      { label: "Data Export Center", href: "/super-admin/exports" },
    ],
    meta: meta("auditor"),
  },
  {
    id: "security-incident-response",
    title: "Security incident response",
    purpose: "Contain and investigate a suspected security incident.",
    whenToUse: "On signs of compromise — unexpected access, anomalies, or abuse.",
    requiredRole: "Owner / Super Admin with Technical Admin",
    steps: [
      "Assess scope and severity before acting.",
      "Contain: revoke suspicious sessions and tighten affected access.",
      "Preserve evidence — export relevant audit records early.",
      "Escalate to the platform owner through your on-call channel.",
      "Remediate the root cause, then document a timeline and follow-ups.",
    ],
    safetyWarnings: [
      "Do not tip off a suspected malicious actor before containment.",
      "Do not destroy or alter evidence while investigating.",
    ],
    approvalRequired: "Owner is informed immediately; major containment steps are owner-directed.",
    auditExpectation: "Containment actions and evidence exports are logged with actor and time.",
    smokeTestCheck: "Suspicious access is confirmed revoked and legitimate access still works.",
    relatedLinks: [
      { label: "Security Center", href: "/super-admin/security" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("owner"),
  },
  {
    id: "failed-job-retry",
    title: "Failed job retry",
    purpose: "Safely retry a failed or stuck background job.",
    whenToUse: "When the Jobs console shows failures or stalled work.",
    requiredRole: "Technical Admin",
    steps: [
      "Open Background Jobs and identify the failed job.",
      "Read what the job does and why it failed before retrying.",
      "Confirm a retry is safe and not duplicative for that job type.",
      "Retry the job.",
      "Confirm it completes; if it fails again, investigate the root cause.",
    ],
    safetyWarnings: [
      "Some jobs are not safe to run twice — understand the job first.",
      "If scheduled jobs are not firing at all, check the worker before retrying.",
    ],
    approvalRequired: null,
    auditExpectation: "Retry actions are logged with actor and job reference.",
    smokeTestCheck: "The retried job reaches a success state.",
    relatedLinks: [
      { label: "Background Jobs", href: "/super-admin/jobs" },
      { label: "Health / Observability", href: "/super-admin/observability" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "communication-broadcast",
    title: "Communication and broadcast",
    purpose: "Send a platform announcement or broadcast safely.",
    whenToUse: "For planned platform-wide or targeted announcements.",
    requiredRole: "Owner / Super Admin",
    steps: [
      "Draft the message and confirm its content and tone.",
      "Preview exactly which recipients it will reach.",
      "Send to a small test audience first for large broadcasts.",
      "Send the broadcast.",
      "Confirm delivery status and that it is recorded.",
    ],
    safetyWarnings: [
      "A broadcast cannot be recalled — treat send as irreversible.",
      "Email needs the optional mail service; without it, delivery is in-app only.",
    ],
    approvalRequired: "Owner approval for platform-wide broadcasts.",
    auditExpectation: "Broadcast creation and send are logged with actor and audience.",
    smokeTestCheck: "The test broadcast reaches the test audience and shows delivery status.",
    relatedLinks: [
      { label: "Communication Admin", href: "/super-admin/communication" },
      { label: "Audit Console", href: "/super-admin/platform/audit" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "deployment-smoke-test",
    title: "Deployment smoke-test",
    purpose: "Confirm the platform is healthy after a deploy.",
    whenToUse: "Immediately after any deployment to production.",
    requiredRole: "Technical Admin",
    steps: [
      "Confirm the deploy reported success and the app is reachable.",
      "Check Observability for healthy signals and no error spikes.",
      "Sign in and load key Super Admin modules.",
      "Run the Full Super Admin regression checklist's read-only checks.",
      "Record the smoke-test result.",
    ],
    safetyWarnings: [
      "Use read-only checks for smoke-testing; do not trigger destructive flows on real data.",
      "If health is red, prepare to roll back rather than pressing on.",
    ],
    approvalRequired: null,
    auditExpectation: "Any actions taken during the smoke test are logged as usual.",
    smokeTestCheck: "Core modules load, health is green, and no new error spike is present.",
    relatedLinks: [
      { label: "Health / Observability", href: "/super-admin/observability" },
      { label: "Platform Overview", href: "/super-admin/platform" },
    ],
    meta: meta("technical_admin"),
  },
  {
    id: "rollback",
    title: "Rollback",
    purpose: "Return the platform to the previous known-good release after a bad deploy.",
    whenToUse: "When a deploy causes failures that a quick fix cannot resolve.",
    requiredRole: "Owner / Super Admin with Technical Admin",
    steps: [
      "Confirm the current release is the cause and forward-fix is not faster.",
      "Identify the previous known-good release.",
      "Take a fresh backup if data may have changed since the deploy.",
      "Execute the rollback to the previous release.",
      "Run the deployment smoke-test to confirm recovery.",
    ],
    safetyWarnings: [
      "Rolling back across a schema change can be unsafe — check migration notes first.",
      "Do not roll back blindly; confirm the previous release is compatible.",
    ],
    approvalRequired: "Owner approval to roll back a production release.",
    auditExpectation: "Rollback decision and execution are logged with actor and target release.",
    smokeTestCheck: "Post-rollback smoke tests pass and the failure symptoms are gone.",
    relatedLinks: [
      { label: "Health / Observability", href: "/super-admin/observability" },
      { label: "Help / SOP Center", href: "/super-admin/help" },
    ],
    meta: meta("owner"),
  },
  {
    id: "disaster-recovery",
    title: "Disaster recovery",
    purpose: "Restore platform service after a major outage or data-loss event.",
    whenToUse: "When the platform is down or data is lost and normal fixes are insufficient.",
    requiredRole: "Owner / Super Admin with Technical Admin",
    steps: [
      "Declare a DR event and assemble the response through your on-call process.",
      "Assess what is lost and identify the most recent known-good backup.",
      "Stand up the recovery environment per your infrastructure runbook.",
      "Follow the restore SOP to recover data from backup, with approval.",
      "Smoke-test thoroughly, then communicate restoration of service.",
    ],
    safetyWarnings: [
      "Coordinate DR through one incident lead to avoid conflicting actions.",
      "Recovery may involve destructive restore — apply all restore safeguards.",
    ],
    approvalRequired: "Platform owner directs the DR effort and approves restores.",
    auditExpectation: "Key DR decisions and restores are logged; a post-incident timeline is retained.",
    smokeTestCheck: "Service is reachable, health is green, and recovered data validates against checks.",
    relatedLinks: [
      { label: "Backup / Restore", href: "/super-admin/backups" },
      { label: "Health / Observability", href: "/super-admin/observability" },
    ],
    meta: meta("owner"),
  },
  {
    id: "emergency-owner-recovery",
    title: "Emergency owner recovery",
    purpose: "Restore platform-owner access when the last owner is locked out.",
    whenToUse: "When no active platform owner can sign in.",
    requiredRole: "Owner / Super Admin (break-glass process)",
    steps: [
      "Confirm no other owner can sign in through normal means.",
      "Verify the requester's identity rigorously, out of band.",
      "Use the approved break-glass procedure from your operations runbook.",
      "Restore a single owner account and require an immediate 2FA enrolment.",
      "Review recent audit activity for anything unexpected during lockout.",
    ],
    safetyWarnings: [
      "Break-glass is high-risk — identity verification must be thorough.",
      "Restore the minimum access needed; do not create extra owners.",
    ],
    approvalRequired: "Break-glass authorisation per your operations runbook.",
    auditExpectation: "The recovery is logged with actor, subject, verification and time.",
    smokeTestCheck: "Exactly one recovered owner can sign in with a fresh second factor.",
    relatedLinks: [
      { label: "Platform Admin Users", href: "/super-admin/admins" },
      { label: "Security Center", href: "/super-admin/security" },
    ],
    meta: meta("owner"),
  },
];
